language: ruby
rvm:
  - 2.1.5
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database kokoro_test' -U postgres
cache: bundler
notifications:
  webhooks:
    urls:
      - http://travis-ci.herokuapp.com/imascg
